spring:
  main.banner-mode: OFF
  datasource:
    username: ${MYSQL_USERNAME:user}
    password: ${MYSQL_PASSWORD:userpass}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dev}?serverTimezone=UTC
  jpa:
    hibernate.ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
  mail:
    x-active: ${MAIL_SENDER_ACTIVE:false}
    username: ${MAIL_SENDER_USERNAME:}
    password: ${MAIL_SENDER_PASSWORD:}
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true

springdoc:
  api-docs:
    path: /v1/api-docs
