body:
  jobCreateRequest:
    required: true
    content:
      application/json:
        schema:
          $ref: '../jobs/components.yaml#/jobCreateData'
  jobUpdateRequest:
    required: true
    content:
      application/json:
        schema:
          $ref: '../jobs/components.yaml#/jobUpdateData'
